/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import BusinessObject.*;
import BusinessLogic.*;
import java.awt.Image;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author singhj1
 */
public class StockManagement extends javax.swing.JFrame {

    List<Used> AllUsed;
    List<Parts> AllParts;
    Used used = new Used();
    Base base = new Base();
    Date date = new Date();
    Map<Integer, Integer> mapGetallParts, mapGetallPeople;
    
    int UpdateId = 0, PartId = 0,PeopleId =0;
    People people;
    Parts parts;
    /**
     * Creates new form StockManagement
     */
    public StockManagement() {
        initComponents();
        GetallParts();
        GetallUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void GetallParts() {
        int a = 0;
        mapGetallParts = new HashMap<Integer, Integer>();
        List<Parts> AllParts = PartsBL.GetAll();
        for (int i = 0; i < AllParts.size(); i++) {

            UserPartSelect.addItem(AllParts.get(i).getName());
            UserSelectPart2.addItem(AllParts.get(i).getName());
            mapGetallParts.put(a, AllParts.get(i).getId());
            a++;

        }

    }

    private void GetallUser() {
        int a = 0;
        mapGetallPeople = new HashMap<Integer, Integer>();
        List<People> AllPeople = PeopleBL.GetAll();
        for (int i = 0; i < AllPeople.size(); i++) {

            UserNameSelect.addItem(AllPeople.get(i).getName());

            mapGetallPeople.put(a, AllPeople.get(i).getID());
            a++;

        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        UserPartSelect = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        UserNameSelect = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        UserSelectPart2 = new javax.swing.JComboBox<>();
        SearchPartDetail = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        SearchData = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        NewQuantity = new javax.swing.JTextField();
        InsertUsed = new javax.swing.JButton();
        UsedImage = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel16.setText("Select Parts");

        jLabel17.setText("Enter Quantity");

        jLabel18.setText("Select User");

        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        SearchPartDetail.setText(" Search By List");
        SearchPartDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPartDetailActionPerformed(evt);
            }
        });

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Part Name", "Quantity Used By User", "Name", "Identity", "", "", ""
            }
        ));
        jTable7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable7MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable7);
        if (jTable7.getColumnModel().getColumnCount() > 0) {
            jTable7.getColumnModel().getColumn(4).setMinWidth(0);
            jTable7.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTable7.getColumnModel().getColumn(4).setMaxWidth(0);
            jTable7.getColumnModel().getColumn(5).setMinWidth(0);
            jTable7.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTable7.getColumnModel().getColumn(5).setMaxWidth(0);
            jTable7.getColumnModel().getColumn(6).setMinWidth(0);
            jTable7.getColumnModel().getColumn(6).setPreferredWidth(0);
            jTable7.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        jButton1.setText("Search By Part Name");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        InsertUsed.setText("Insert");
        InsertUsed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertUsedActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(InsertUsed)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UsedImage, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(UserPartSelect, 0, 168, Short.MAX_VALUE)
                    .addComponent(UserNameSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9))
                    .addComponent(NewQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SearchData, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserSelectPart2, javax.swing.GroupLayout.Alignment.LEADING, 0, 205, Short.MAX_VALUE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchPartDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserPartSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(NewQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserSelectPart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchPartDetail))
                        .addGap(22, 22, 22)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(UserNameSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton9)
                            .addComponent(InsertUsed))
                        .addGap(74, 74, 74)
                        .addComponent(UsedImage, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Stock Management", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertUsedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertUsedActionPerformed
        // TODO add your handling code here:

        
        int partId = mapGetallParts.get(UserPartSelect.getSelectedIndex());
        int peopleId = mapGetallPeople.get(UserNameSelect.getSelectedIndex());
        
        used.setCount(NewQuantity.getText()); 
        used.setPartId(partId);
        used.setPeopleId(peopleId);
        
        base.setIsApproved("yes");
        base.setIsDeleted("no");
        base.setCreatedOn(date.toString());
        
        used.setBase(base);
        UsedBL.Add(used);

    }//GEN-LAST:event_InsertUsedActionPerformed

    private void SearchPartDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPartDetailActionPerformed
        // TODO add your handling code here:
        
        int partId = mapGetallParts.get(UserSelectPart2.getSelectedIndex());
        
        List<Used> list = UsedBL.GetAllByPartId(partId);
        DefaultTableModel tablemodel = (DefaultTableModel) jTable7.getModel();
        tablemodel.setRowCount(0);
        
        Object[] row = new Object[7];

        for (int i = 0; i < list.size(); i++) {

            people = PeopleBL.GetSingle(list.get(i).getPeopleId());
            parts = PartsBL.GetSingle(list.get(i).getPartId());
            
            row[0] = parts.getName();
            row[1] = list.get(i).getCount();
            row[2] = people.getName();
            row[3] = people.getIdentified();
            row[4] = list.get(i).getId();
            row[5] = people.getID();
            row[6] = parts.getId();
           
            tablemodel.addRow(row);

        }
    }//GEN-LAST:event_SearchPartDetailActionPerformed

    private void jTable7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable7MouseClicked
        // TODO add your handling code here:
        
        UpdateId = 0;
        PeopleId = 0;
        PartId = 0;
        
        int rowId = jTable7.getSelectedRow();
        TableModel model = jTable7.getModel();
        
        
        PartId = (int)model.getValueAt(rowId, 6);
        PeopleId = (int)model.getValueAt(rowId, 5);
        
        people = PeopleBL.GetSingle(PeopleId);
        
       ImageIcon image = new ImageIcon(new ImageIcon(people.getImage()).getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH));
       UsedImage.setText("");
       UsedImage.setIcon(image);
        
        NewQuantity.setText(model.getValueAt(rowId, 1).toString());
        
        UpdateId = (int)model.getValueAt(rowId, 4);
        
        
        
    }//GEN-LAST:event_jTable7MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        PeopleId = 0;
        PartId = 0;
        
        PartId = mapGetallParts.get(UserPartSelect.getSelectedIndex());
        PeopleId = mapGetallPeople.get(UserNameSelect.getSelectedIndex());
        
        used.setPartId(PartId);
        used.setPeopleId(PeopleId);
        used.setCount(NewQuantity.getText());
        
        base.setIsApproved("yes");
        base.setIsDeleted("no");
        base.setCreatedOn(date.toString());
        
        used.setBase(base);
        used.setId(UpdateId);
        
        UsedBL.Update(used);
        
        
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
        used.setId(UpdateId);
        
        UsedBL.Delete(used);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         AllParts= PartsBL.Search(SearchData.getText());
        
    
       
        DefaultTableModel tablemodel = (DefaultTableModel) jTable7.getModel();
        tablemodel.setRowCount(0);
        
        Object[] row = new Object[7];

        for (int i = 0; i < AllParts.size(); i++) {

           
            row[0] = AllParts.get(i).getName();
            row[1] = "";
            row[2] = people.getName();
            row[3] = people.getIdentified();
            row[4] = "";
            row[5] = people.getID();
            row[6] = AllParts.get(i).getId();
           
            tablemodel.addRow(row);

        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Search search = new Search();
        search.setVisible(true);
        search.setLocationRelativeTo(null);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertUsed;
    private javax.swing.JTextField NewQuantity;
    private javax.swing.JTextField SearchData;
    private javax.swing.JButton SearchPartDetail;
    private javax.swing.JLabel UsedImage;
    private javax.swing.JComboBox<String> UserNameSelect;
    private javax.swing.JComboBox<String> UserPartSelect;
    private javax.swing.JComboBox<String> UserSelectPart2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable7;
    // End of variables declaration//GEN-END:variables
}
