/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facebookgui;

import facebook4j.Message;
import facebook4j.Photo;

/**
 *
 * @author jaswinder
 */
public class AllObjects extends javax.swing.JFrame {

    /**
     * Creates new form AllObjects
     */
    public AllObjects() {
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FavouritButton = new javax.swing.JButton();
        MessageButton = new javax.swing.JButton();
        PostButton = new javax.swing.JButton();
        AlbumButton = new javax.swing.JButton();
        FriendButton = new javax.swing.JButton();
        LocationButton = new javax.swing.JButton();
        UserButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FavouritButton.setText("Favourite");
        FavouritButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavouritButtonActionPerformed(evt);
            }
        });

        MessageButton.setText("Message");
        MessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessageButtonActionPerformed(evt);
            }
        });

        PostButton.setText("Post");
        PostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostButtonActionPerformed(evt);
            }
        });

        AlbumButton.setText("Album");
        AlbumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlbumButtonActionPerformed(evt);
            }
        });

        FriendButton.setText("Friend");
        FriendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriendButtonActionPerformed(evt);
            }
        });

        LocationButton.setText("Location");
        LocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationButtonActionPerformed(evt);
            }
        });

        UserButton.setText("User");
        UserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserButtonActionPerformed(evt);
            }
        });

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Click any button to get result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AlbumButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FavouritButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MessageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LocationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FriendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PostButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FavouritButton)
                    .addComponent(AlbumButton)
                    .addComponent(LocationButton))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MessageButton)
                    .addComponent(SearchButton)
                    .addComponent(FriendButton))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PostButton)
                    .addComponent(UserButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlbumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlbumButtonActionPerformed
        // TODO add your handling code here:
        Album album = new Album();
        album.setVisible(true);
        album.setLocationRelativeTo(null);
        
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_AlbumButtonActionPerformed

    private void FavouritButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavouritButtonActionPerformed
        // TODO add your handling code here:
        
        Favourite favourite = new Favourite();
        favourite.setVisible(true);
        favourite.setLocationRelativeTo(null);
        this.setVisible(false);
        this.dispose();
        
        
    }//GEN-LAST:event_FavouritButtonActionPerformed

    private void FriendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriendButtonActionPerformed
        // TODO add your handling code here:
        
        Friends friends = new Friends();
        friends.setVisible(true);
        friends.setLocationRelativeTo(null);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_FriendButtonActionPerformed

    private void LocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationButtonActionPerformed
        // TODO add your handling code here:
        
      Location location = new Location();
      location.setVisible(true);
      location.setLocationRelativeTo(null);
      this.setVisible(false);
      this.dispose();
        
    }//GEN-LAST:event_LocationButtonActionPerformed

    private void MessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessageButtonActionPerformed
        // TODO add your handling code here:
        
        Messages message = new Messages();
        message.setVisible(true);
        message.setLocationRelativeTo(null);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_MessageButtonActionPerformed

    private void UserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserButtonActionPerformed
        // TODO add your handling code here:
        
        Users users = new Users();
        users.setVisible(true);
        users.setLocationRelativeTo(null);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_UserButtonActionPerformed

    private void PostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostButtonActionPerformed
        // TODO add your handling code here:
        Posts posts = new Posts();
        posts.setVisible(true);
        posts.setLocationRelativeTo(null);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_PostButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        
        Searches search = new Searches();
        search.setVisible(true);
        search.setLocationRelativeTo(null);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_SearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllObjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlbumButton;
    private javax.swing.JButton FavouritButton;
    private javax.swing.JButton FriendButton;
    private javax.swing.JButton LocationButton;
    private javax.swing.JButton MessageButton;
    private javax.swing.JButton PostButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UserButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
