/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facebookgui;

import facebook4j.Facebook;
import facebook4j.FacebookFactory;
import facebook4j.PagableList;
import facebook4j.Photo;
import facebook4j.ResponseList;
import facebook4j.conf.ConfigurationBuilder;

/**
 *
 * @author jaswinder
 */
public class Comment extends javax.swing.JFrame {

    /**
     * Creates new form Comment
     */
    private final static String AppId = "939873682746936";
    private final static String AppSecret ="425b3f54eff413c7715395cc9822d267";
        
    public Comment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        GetCommentPhotoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GetCommentPhotoTextArea = new javax.swing.JTextArea();
        GetCommentPhotoTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Comment");

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        GetCommentPhotoButton.setText("Get Comment");
        GetCommentPhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetCommentPhotoButtonActionPerformed(evt);
            }
        });

        GetCommentPhotoTextArea.setColumns(20);
        GetCommentPhotoTextArea.setRows(5);
        jScrollPane1.setViewportView(GetCommentPhotoTextArea);

        GetCommentPhotoTextField.setText("Photo Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GetCommentPhotoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GetCommentPhotoTextField))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BackButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetCommentPhotoButton)
                    .addComponent(GetCommentPhotoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        
        AllObjects allobject  = new AllObjects();
        allobject.setVisible(true);
        allobject.setLocationRelativeTo(null);
        
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_BackButtonActionPerformed

    private void GetCommentPhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetCommentPhotoButtonActionPerformed
        // TODO add your handling code here:
        
        ConfigurationBuilder cb = new ConfigurationBuilder();
     cb.setDebugEnabled(true)
    .setOAuthAppId(AppId)
    .setOAuthAppSecret(AppSecret)
    .setOAuthAccessToken(Home.AccessToken);
    
    FacebookFactory ff = new FacebookFactory(cb.build());
    Facebook facebook = ff.getInstance();
      
        try {
            
            if (GetCommentPhotoTextArea.getText() == " ") {
                
                ResponseList<facebook4j.Album> pic =  facebook.getAlbums(facebook.getId());
   
        for (facebook4j.Album album : pic) {
            
            ResponseList<Photo> photos = facebook.getAlbumPhotos(album.getId());
            
            for (Photo photo : photos) {
                
                PagableList<facebook4j.Comment> comms = photo.getComments();
                
                for(facebook4j.Comment comm : comms){
                
                    GetCommentPhotoTextArea.append(comm.getMessage() +"\n");
                }
            }
        } 
            }else {
                
            ResponseList<Photo> photos = facebook.getAlbumPhotos(GetCommentPhotoTextField.getText());
            
            for (Photo photo : photos) {
                
                PagableList<facebook4j.Comment> comms = photo.getComments();
                
                for(facebook4j.Comment comm : comms){
                
                    GetCommentPhotoTextArea.append(comm.getMessage() +"\n");
                }
            }    
                }
            
            
        } catch (Exception e) {
        
        GetCommentPhotoTextArea.append(e.getMessage());
        }
        
    }//GEN-LAST:event_GetCommentPhotoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton GetCommentPhotoButton;
    private javax.swing.JTextArea GetCommentPhotoTextArea;
    private javax.swing.JTextField GetCommentPhotoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
